Repository ImanYZ/VisualExp, pull requests merged in 2022-12, with the labels that each got.

#572 E·nhancement for the feedback coding component
  expHome/functions/projectManagement.js
  expHome/src/App.js
  expHome/src/Components/Auth/SignUpPage.js
  expHome/src/Components/ProjectManagement/CodeFeedback/CodeFeedback.drawio
  expHome/src/Components/ProjectManagement/CodeFeedback/CodeFeedback.js
Labels: enhancement

#585 Feature/add home page animation
  expHome/package.json
  expHome/public/gg.old.riv
  expHome/public/gg.old1.riv
  expHome/public/gg.riv
  expHome/src/App.css
  expHome/src/Components/Home/Home.js
  expHome/src/Components/Home/hooks/useWindowSize.js
  expHome/src/Components/Home/modules/views/AppAppBar.js
  expHome/src/Components/Home/modules/views/HowItWorks.js
  expHome/src/assets/rive/gg.riv
Labels: enhancement

#587 fix animations file
  expHome/public/gg.old2.riv
  expHome/public/gg.riv
Labels: enhancement

#595 Feature/add home page animation
  expHome/public/static/Balanced_Perspectives.old.png
  expHome/public/static/Balanced_Perspectives.png
  expHome/public/static/Search_for_Learning.old.png
  expHome/public/static/Search_for_Learning.png
  expHome/src/App.css
  expHome/src/Components/Home/Home.js
  expHome/src/Components/Home/modules/components/TableOfContent.js
  expHome/src/Components/Home/modules/views/JoinUs.js
  expHome/src/Components/Home/modules/views/UniversitiesMap/UniversitiesMap.js
  expHome/src/Components/Home/modules/views/Values.js
  expHome/src/Components/Home/modules/views/What.js
  expHome/src/Components/Home/modules/views/WhoWeAre.js
  expHome/src/Components/Home/modules/views/sectionsOrder.js
Labels: bug, enhancement

#599 The user cannot fill the demographic info in the Experiment
  expHome/src/Components/Auth/Auth.js
  expHome/src/Components/Auth/SignUpPage.js
  expHome/src/Components/PersonalInfo/DateAndGenderPickers.js
Labels: bug

#602 Feature/add home page animation
  expHome/animations-backup/1Cademy-1.4.0.rev
  expHome/animations-backup/1Cademy-1.5.0.rev
  expHome/animations-backup/README.md
  expHome/public/gg.riv
  expHome/src/Components/Home/Home.js
  expHome/src/Components/Home/modules/components/TableOfContent.js
  expHome/src/Components/Home/modules/views/HowItWorks.js
  expHome/src/Components/Home/modules/views/WhoWeAre.js
  expHome/src/assets/rive/gg.riv
Labels: bug, enhancement

#606 change initial text in animation
  expHome/public/gg.riv
Labels: enhancement

#604 Experiment session flow optimized
  expHome/src/App.js
  expHome/src/AppRouter.js
  expHome/src/Components/MCQuestion/MCQuestion.js
  expHome/src/Components/Passage/PassageLeft.js
  expHome/src/Components/Passage/PassageRight.js
  expHome/src/Components/Passage/PostQuestionsPage.js
  expHome/src/Components/ProjectManagement/ManageEvents/ManageEvents.js
  expHome/src/Components/SchedulePage/ScheduleAdministratorPage.js
  expHome/src/Components/SchedulePage/ScheduleInstructorPage.js
  expHome/src/Components/SchedulePage/SchedulePage.js
  expHome/src/Components/YoutubeAutoplayIframe.js
  expHome/src/store/ExperimentAtoms.js
Labels: enhancement

#609 Sign up page style fixed and personal info made responsive for tablet view
  expHome/src/Components/Auth/SignUpPage.js
  expHome/src/Components/Passage/PassageRight.js
  expHome/src/Components/PersonalInfo/PersonalInfo.js
  expHome/src/store/ExperimentAtoms.js
Labels: enhancement

#612 Signup and auth flow optimizations
  expHome/firebase.json
  expHome/functions/.env.test
  expHome/functions/__tests__/api/signUp.test.js
  expHome/functions/admin.js
  expHome/functions/admin_Knowledge.js
  expHome/functions/api/signUp.js
  expHome/functions/app.js
  expHome/functions/index.js
  expHome/functions/jest.config.js
  expHome/functions/package.json
  expHome/functions/testUtils/MockData.js
  expHome/functions/testUtils/deleteAllUsers.js
  expHome/functions/testUtils/index.js
  expHome/functions/testUtils/isTestEnv.js
  expHome/functions/testUtils/mockCollections/conditions.data.js
  expHome/functions/testUtils/mockCollections/passages.data.js
  expHome/functions/testUtils/mockCollections/projectSpecs.data.js
  expHome/package.json
  expHome/src/App.js
  expHome/src/AppRouter.js
  expHome/src/Components/Auth/Auth.js
  expHome/src/Components/Auth/AuthStudentCoNoteSurvey.js
  expHome/src/Components/Auth/SignUpPage.js
  expHome/src/Components/Home/Home.js
  expHome/src/Components/Home/modules/views/UniversitiesMap/UniversitiesMap.js
  expHome/src/Components/firebase/firebase.js
  expHome/src/store/AuthAtoms.js
  expHome/src/store/GlobalAtoms.js
  expHome/src/utils/CosineSimilarity.js
  expHome/src/utils/DateFunctions.js
  expHome/src/utils/helpers.js
  expHome/src/utils/index.js
Labels: bug, enhancement

#614 Feature/add home page animation
  expHome/public/artboard-1.riv
  expHome/public/artboard-2.riv
  expHome/public/artboard-3.riv
  expHome/public/artboard-4.riv
  expHome/public/artboard-5.riv
  expHome/public/artboard-6.riv
  expHome/src/App.css
  expHome/src/Components/Home/Home.js
  expHome/src/Components/Home/modules/hooks/useRiveAnimations.js
  expHome/src/Components/Home/modules/views/HowItWorks.js
  expHome/src/Components/Home/modules/views/WhoWeAre.js
  expHome/src/animations.css
  expHome/src/assets/AnimatediconLoop.gif
  expHome/src/assets/AnimatediconLoop.old-sm.gif
  expHome/src/assets/AnimatediconLoop.old.gif
  expHome/src/assets/DarkModeLogoMini.png
  expHome/src/assets/darkModeLibraryBackground.jpg
Labels: bug, enhancement

#625 Experiement Test flow on each PR
  .github/workflows/experimentTesting.yml
  expHome/functions/admin_Knowledge.js
  expHome/functions/jest.config.js
  expHome/functions/package.json
Labels: enhancement

#632 update the criteria in the leaderboard
  expHome/src/Components/ProjectManagement/Activities/components/ProjectPointThresholds.js
Labels: invalid

#638 Feature/improve home page animation
  expHome/public/artboard-1.riv
  expHome/public/artboard-2.riv
  expHome/public/artboard-3.riv
  expHome/public/artboard-4.riv
  expHome/public/artboard-5.riv
  expHome/public/artboard-6.riv
  expHome/public/static/Research_Communities.old.png
  expHome/public/static/Research_Communities.png
  expHome/src/Components/Home/Home.js
  expHome/src/Components/Home/modules/components/TableOfContent.js
  expHome/src/Components/Home/modules/hooks/useObserver.js
  expHome/src/Components/Home/modules/hooks/useRiveAnimations.js
  expHome/src/Components/Home/modules/views/HowItWorks.js
  expHome/src/Components/Home/modules/views/JoinUs.js
  expHome/src/Components/Home/modules/views/JoinUsWrapper.js
  expHome/src/Components/Home/modules/views/UniversitiesMap/UniversitiesMap.js
  expHome/src/Components/Home/modules/views/Values.js
  expHome/src/Components/Home/modules/views/What.js
  expHome/src/Components/Home/modules/views/WhoWeAre.js
  expHome/src/Components/Home/modules/views/WhoWeAreWrapper.js
  expHome/src/animations.css
Labels: bug, enhancement

#644 Task/557 exp sessions earned points
  expHome/functions/projectManagement.js
  expHome/src/Components/Home/modules/views/communitiesPapers.js
Labels: bug
