Repository ImanYZ/VisualExp, pull requests merged in 2022-10, with the labels that each got.

#530 Create an account step in homepage
  expHome/src/Components/Home/modules/views/JoinUs.js
Labels: enhancement

#531 added the schema generation tool to the Experiment activities
  expHome/firestore.rules
  expHome/functions/projectManagement.js
  expHome/package.json
  expHome/src/AppRouter.js
  expHome/src/Components/ProjectManagement/Activities/Activities.js
  expHome/src/Components/ProjectManagement/Passage-Research/ResearcherPassage.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/QueryBuilder.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGeneration.css
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGeneration.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/index.js
  expHome/src/Components/RouterNav/RouterNav.js
  expHome/src/index.css
Labels: enhancement

#534 Fix a bug in the SignIn/SignUp page the page keep reloading when the user signIn
  expHome/src/Components/Auth/Auth.js
  expHome/src/Components/Auth/SignUpPage.js
Labels: bug

#543 Store the last passage and phrase for which the researcher was working on. So that the next time the researcher logs in, they can continue from where they left off.
  expHome/firestore.rules
  expHome/src/Components/ProjectManagement/Activities/Activities.js
  expHome/src/Components/ProjectManagement/Activities/components/ProjectPointThresholds.js
  expHome/src/Components/ProjectManagement/FreeRecallGrading/FreeRecallGrading.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGeneration.js
  expHome/src/Components/RouterNav/RouterNav.js
Labels: bug, enhancement

#550 fix issues in the QuerySearching
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGeneration.css
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGeneration.js
Labels: enhancement

#552 fix bugs in the `applicationReminder` PubSub
  expHome/functions/users.js
Labels: bug

#556 fix bug in the alternatives keywords not getting updated
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGeneration.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/components/ChipInput.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/components/QueryBox.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/components/QueryBuilder.js
Labels: bug

#567 Because we changed the data structure of onecademy it shows all the researchers' points in all the projects as 0
  expHome/src/Components/RouterNav/RouterNav.js
Labels: bug
