Repository ImanYZ/VisualExp, pull requests merged in 2023-03, with the labels that each got.

#852 recall grading snapshot implementation
  expHome/functions/__tests__/api/researchers/gradeRecalls.test.js
  expHome/functions/actions/researchers/gradeRecalls.js
  expHome/src/Components/ProjectManagement/FreeRecallGrading/FreeRecallGrading.js
  expHome/src/utils/helpers.js
Labels: bug, enhancement

#880 Priority field added in recall grading documents
  expHome/src/App.js
Labels: enhancement

#893 recall upload endpoint
  expHome/functions/actions/recallUpload.js
  expHome/functions/app.js
Labels: enhancement

#895 recall upload endpoint
  expHome/functions/actions/recallUpload.js
Labels: enhancement

#896 recall upload endpoint
  expHome/functions/actions/recallUpload.js
Labels: enhancement

#919 Resolve instructors voting bugs
  expHome/src/Components/ProjectManagement/AddInstructor/AddInstructor.js
Labels: bug

#921 change the researchers Page to use RecallGradesV2 instead and fix a bug in the feedbackCode
  expHome/functions/projectManagement.js
  expHome/src/Components/DissertationGantt.js
  expHome/src/Components/ProjectManagement/Passage-Research/ResearcherPassage.js
Labels: bug

#923 Modify the csv file generator to generate records for the gpt4
  expHome/src/Components/ProjectManagement/FreeRecallGrading/RecallForIman.js
  localFunctions/visualExp.js
Labels: enhancement

#926 added a legend to help the users relate the colors with the resources.
  expHome/src/Components/DissertationGantt.js
Labels: enhancement

#960 Fix issues in the boolean SchemaGeneration Page regarding the order (updates from develop)
  expHome/src/Components/ProjectManagement/FreeRecallGrading/FreeRecallGrading.js
  expHome/src/Components/ProjectManagement/FreeRecallGrading/RecallForIman.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGenRecalls.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGeneration.css
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGeneration.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/components/ChipInput.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/components/QueryBox.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/components/QueryBuilder.js
  localFunctions/visualExp.js
Labels: bug, enhancement

#982 update the communities urls
  expHome/src/Components/Home/modules/views/JoinUs.js
Labels: bug

#985 fix issues with grading the recallGrades and the coding the feedbackc…
  expHome/firestore.indexes.json
  expHome/functions/__tests__/helpers/assignExpPoints.test.js
  expHome/functions/actions/researchers/codeFeedback.js
  expHome/functions/actions/researchers/gradeRecalls.js
  expHome/functions/app.js
  expHome/functions/helpers/assignExpPoints.js
  expHome/functions/projectManagement.js
  expHome/functions/testUtils/index.js
  expHome/functions/testUtils/writeTransaction.js
  expHome/src/Components/ProjectManagement/CodeFeedback/CodeFeedback.js
Labels: bug

#1001 fix the pubsub that's calculating the number of particpants in each passage
  expHome/functions/projectManagement.js
Labels: bug
