Repository ImanYZ/VisualExp, pull requests merged in 2023-02, with the labels that each got.

#744 Bug fixes in Experiement Sessions
  .github/workflows/experimentTesting.yml
  expHome/.env.production
  expHome/firestore.rules
  expHome/functions/GoogleCalendar.js
  expHome/functions/scheduling.js
  expHome/src/App.js
  expHome/src/AppRouter.js
  expHome/src/Components/Home/Communities.js
Labels: enhancement

#745 removed invalid statement from App.js
  .github/workflows/experimentTesting.yml
  expHome/.env.production
  expHome/src/App.js
Labels: enhancement

#746 Remove unnecessory code
  .github/workflows/experimentTesting.yml
  expHome/.env.production
  expHome/src/App.js
Labels: enhancement

#787 fixed scheduling experiment issues
  expHome/functions/api/participants.js
  expHome/src/Components/SchedulePage/SchedulePage.js
Labels: bug, enhancement

#789 fix issues applying to communities : participant finished the 3 research experiments but for some reason, I'm having trouble applying for the internship
  expHome/src/AppRouter.js
  expHome/src/Components/Home/Communities.js
  expHome/src/Components/Home/modules/views/JoinUs.js
Labels: bug, enhancement

#802 added suitable selector to recall grading and schema generation page
  expHome/src/Components/ProjectManagement/FreeRecallGrading/FreeRecallGrading.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGenRecalls.js
Labels: enhancement

#803 added suitable selector to recall grading and schema generation page
  expHome/src/Components/ProjectManagement/FreeRecallGrading/FreeRecallGrading.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGenRecalls.js
Labels: enhancement

#809 ignored points distribution for gpt recall grading
  expHome/functions/__tests__/api/researchers/gradeRecalls.test.js
  expHome/functions/actions/researchers/gradeRecalls.js
  expHome/functions/testUtils/mockCollections/researchers.data.js
  expHome/src/Components/ProjectManagement/FreeRecallGrading/FreeRecallGrading.js
Labels: enhancement

#810 ignored gpt researcher from point distribution of recall grading
  expHome/functions/__tests__/api/researchers/gradeRecalls.test.js
  expHome/functions/actions/researchers/gradeRecalls.js
  expHome/functions/testUtils/mockCollections/researchers.data.js
  expHome/src/Components/ProjectManagement/FreeRecallGrading/FreeRecallGrading.js
Labels: enhancement

#831 Task/817 recall grades page issue
  expHome/src/Components/Auth/SignUpPage.js
  expHome/src/utils/researcher.js
Labels: bug
