Repository ImanYZ/VisualExp, pull requests merged in 2023-01, with the labels that each got.

#649 increased memory limit for ci
  expHome/cloudbuild.yaml
Labels: enhancement

#651 N1 to E2 variant in cloudbuild
  expHome/cloudbuild.yaml
Labels: enhancement

#626 scheduler collection structure and implement on frontend
  .gitguardian.yml
  expHome/functions/__tests__/api/researchers.test.js
  expHome/functions/api/researchers.js
  expHome/functions/app.js
  expHome/functions/testUtils/firestore.js
  expHome/functions/testUtils/index.js
  expHome/functions/testUtils/mockCollections/users.data.js
  expHome/src/AppRouter.js
  expHome/src/Components/Home/Home.js
  expHome/src/Components/Home/modules/views/AppAppBar.js
  expHome/src/Components/ProjectManagement/ExperimentPoints/ExperimentPoints.js
  expHome/src/Components/RouterNav/RouterNav.js
  expHome/src/Components/SchedulePage/SchedulePage.css
  expHome/src/Components/SchedulePage/SchedulePage.js
  expHome/src/Components/SchedulePage/SelectSessions.js
  expHome/src/store/ProjectAtoms.js
Labels: enhancement

#657 participants calendar and auth middleware applied on backend and frontend
  expHome/functions/.env.test
  expHome/functions/.gitignore
  expHome/functions/GoogleCalendar.js
  expHome/functions/__tests__/api/participants.test.js
  expHome/functions/__tests__/api/researchers.test.js
  expHome/functions/api/participants.js
  expHome/functions/api/researchers.js
  expHome/functions/app.js
  expHome/functions/jest.config.js
  expHome/functions/middlewares/firebaseAuth.js
  expHome/functions/middlewares/isParticipant.js
  expHome/functions/middlewares/isResearcher.js
  expHome/functions/package.json
  expHome/functions/scheduling.js
  expHome/functions/testUtils/gtCalendar.js
  expHome/functions/testUtils/index.js
  expHome/functions/testUtils/mockCollections/projectSpecs.data.js
  expHome/functions/testUtils/mockCollections/resSchedule.data.js
  expHome/functions/testUtils/mockCollections/researchers.data.js
  expHome/functions/testUtils/mockCollections/users.data.js
  expHome/src/AppRouter.js
  expHome/src/Components/ProjectManagement/ExperimentPoints/ExperimentPoints.js
  expHome/src/Components/SchedulePage/SchedulePage.js
Labels: bug, enhancement

#663 RecallGrades implemention
  expHome/firestore.rules
  expHome/functions/__tests__/api/researchers/gradeRecalls.test.js
  expHome/functions/__tests__/api/researchers/schedule.test.js
  expHome/functions/actions/researchers/gradeRecalls.js
  expHome/functions/api/researchers.js
  expHome/functions/app.js
  expHome/functions/helpers/passage.js
  expHome/functions/middlewares/firebaseAuth.js
  expHome/functions/projectManagement.js
  expHome/functions/testUtils/index.js
  expHome/functions/testUtils/mockCollections/booleanScratch.data.js
  expHome/functions/testUtils/mockCollections/recallGradesV2.data.js
  expHome/functions/testUtils/mockCollections/researchers.data.js
  expHome/functions/testUtils/mockCollections/users.data.js
  expHome/src/App.js
  expHome/src/AppRouter.js
  expHome/src/Components/ProjectManagement/Activities/components/LeaderBoard.js
  expHome/src/Components/ProjectManagement/ExperimentPoints/ExperimentPoints.js
  expHome/src/Components/ProjectManagement/FreeRecallGrading/FreeRecallGrading.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGenRecalls.js
Labels: bug, enhancement

#664 removed researchers list without sessions/conditions
  expHome/src/Components/ProjectManagement/FreeRecallGrading/FreeRecallGrading.js
Labels: enhancement

#666 aligning develop with master
  expHome/src/AppRouter.js
  localFunctions/.gitignore
Labels: enhancement

#667 recall schema related fixes
  expHome/src/Components/ProjectManagement/Activities/Activities.css
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGenRecalls.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGeneration.css
  expHome/src/Components/ProjectManagement/SchemaGeneration/components/QueryBox.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/components/QueryBox/SchemaInput.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/components/QueryBuilder.js
Labels: enhancement

#672 assign experiment sessions points
  expHome/functions/GoogleCalendar.js
  expHome/functions/__tests__/helpers/assignExpPoints.test.js
  expHome/functions/actions/researchers/gradeRecalls.js
  expHome/functions/helpers/assignExpPoints.js
  expHome/functions/helpers/common.js
  expHome/functions/index.js
  expHome/functions/package.json
  expHome/functions/projectManagement.js
  expHome/functions/scheduling.js
  expHome/functions/testUtils/index.js
  expHome/functions/testUtils/mockCollections/feedbackCode.data.js
  expHome/functions/testUtils/mockCollections/researchers.data.js
  expHome/functions/testUtils/mockCollections/schedule.data.js
  expHome/src/Components/Home/modules/views/communitiesOrder.js
  expHome/src/Components/PersonalInfo/PersonalInfo.js
Labels: enhancement

#673 enhancements in grade recall and assignment of experiement session points
  expHome/firestore.rules
  expHome/functions/GoogleCalendar.js
  expHome/functions/__tests__/api/researchers/gradeRecalls.test.js
  expHome/functions/__tests__/api/researchers/schedule.test.js
  expHome/functions/__tests__/helpers/assignExpPoints.test.js
  expHome/functions/actions/researchers/gradeRecalls.js
  expHome/functions/api/researchers.js
  expHome/functions/app.js
  expHome/functions/helpers/assignExpPoints.js
  expHome/functions/helpers/common.js
  expHome/functions/helpers/passage.js
  expHome/functions/index.js
  expHome/functions/middlewares/firebaseAuth.js
  expHome/functions/package.json
  expHome/functions/projectManagement.js
  expHome/functions/scheduling.js
  expHome/functions/testUtils/index.js
  expHome/functions/testUtils/mockCollections/booleanScratch.data.js
  expHome/functions/testUtils/mockCollections/feedbackCode.data.js
  expHome/functions/testUtils/mockCollections/recallGradesV2.data.js
  expHome/functions/testUtils/mockCollections/researchers.data.js
  expHome/functions/testUtils/mockCollections/schedule.data.js
  expHome/functions/testUtils/mockCollections/users.data.js
  expHome/src/App.js
  expHome/src/AppConfig.js
  expHome/src/AppRouter.js
  expHome/src/Components/PersonalInfo/PersonalInfo.js
  expHome/src/Components/ProjectManagement/Activities/Activities.css
  expHome/src/Components/ProjectManagement/Activities/components/LeaderBoard.js
  expHome/src/Components/ProjectManagement/ExperimentPoints/ExperimentPoints.js
  expHome/src/Components/ProjectManagement/FreeRecallGrading/FreeRecallGrading.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGenRecalls.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGeneration.css
  expHome/src/Components/ProjectManagement/SchemaGeneration/components/QueryBox.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/components/QueryBox/SchemaInput.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/components/QueryBuilder.js
  localFunctions/index.js
  localFunctions/visualExp.js
Labels: enhancement

#682 feedback coding improved
  expHome/functions/projectManagement.js
  expHome/src/App.js
  expHome/src/Components/ProjectManagement/CodeFeedback/CodeFeedback.js
  expHome/src/Components/ProjectManagement/FreeRecallGrading/FreeRecallGrading.js
  expHome/src/utils/researcher.js
  localFunctions/visualExp.js
Labels: bug, enhancement

#689 fixed feedback code component to load previous feedback codes
  expHome/src/Components/ProjectManagement/CodeFeedback/CodeFeedback.js
Labels: enhancement

#692 Boolean exp matching algorithum fixed and showed full paragraph with highlights
  expHome/src/Components/ProjectManagement/FreeRecallGrading/FreeRecallGrading.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGenRecalls.js
Labels: enhancement

#695 fixed logic for switching next phrase
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGenRecalls.js
Labels: enhancement

#699 participant reschedule endpoint bug fix
  expHome/functions/api/participants.js
Labels: enhancement

#697 fixed font color for join us section in dark theme
  expHome/src/Components/Home/Home.js
  expHome/src/Components/Home/modules/views/JoinUs.js
Labels: enhancement

#700 Improvements from develop
  expHome/functions/actions/researchers/gradeRecalls.js
  expHome/functions/api/participants.js
  expHome/src/Components/Home/Home.js
  expHome/src/Components/Home/modules/views/JoinUs.js
  expHome/src/Components/ProjectManagement/CodeFeedback/CodeFeedback.js
  expHome/src/Components/ProjectManagement/FreeRecallGrading/FreeRecallGrading.js
  expHome/src/Components/ProjectManagement/SchemaGeneration/SchemaGenRecalls.js
Labels: enhancement

#702 rules for feedback code order v2
  expHome/firestore.rules
Labels: enhancement

#704 Fixed application reminders for community leaders, iman and applicants
  expHome/functions/__tests__/functions/users/applicationReminder.test.js
  expHome/functions/testUtils/index.js
  expHome/functions/testUtils/mockCollections/applications.data.js
  expHome/functions/testUtils/mockCollections/users.data.js
  expHome/functions/users.js
Labels: enhancement

#707 emailing helper bug fix
  expHome/functions/emailing.js
Labels: enhancement

#708 email helper bug fix
  expHome/functions/emailing.js
Labels: enhancement

#710 feedback code page fixed when codeIds are empty
  expHome/functions/projectManagement.js
  expHome/src/Components/ProjectManagement/CodeFeedback/CodeFeedback.js
Labels: enhancement

#711 feedback code improvements
  expHome/functions/projectManagement.js
  expHome/src/App.js
  expHome/src/Components/ProjectManagement/CodeFeedback/CodeFeedback.js
Labels: enhancement

#712 update natural language processing community
  expHome/src/Components/Home/modules/views/communitiesOrder.js
Labels: documentation

#720 add link extension
  expHome/src/Components/Home/modules/views/communitiesOrder.js
  expHome/src/Components/Home/modules/views/whichItems.js
Labels: enhancement

#721 merge to main
  expHome/src/Components/Home/modules/views/communitiesOrder.js
  expHome/src/Components/Home/modules/views/whichItems.js
Labels: enhancement

#723 Community navigation fixed from Homepage
  expHome/src/Components/Home/modules/views/What.js
Labels: enhancement

#725 Application reminder logic fixed
  expHome/functions/__tests__/functions/users/applicationReminder.test.js
  expHome/functions/testUtils/mockCollections/users.data.js
  expHome/functions/users.js
Labels: enhancement
